### ISSUE TITLE
Error in recorder.bsf

### ISSUE THREAD

**Issue by jgupta** [moodlehq/moodle-performance-comparison#42]
Using Centos 6.4 64-bit
java version 1.7.0_45
apache-jmeter-2.11

-------------ERROR LOG--------------
2014/01/13 00:54:49 INFO  - jmeter.threads.JMeterThread: Thread started: Moodle Test 2-3
2014/01/13 00:54:49 INFO  - jmeter.threads.ThreadGroup: Started thread group number 2
2014/01/13 00:54:49 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started
2014/01/13 00:54:50 ERROR - jmeter.util.BeanShellInterpreter: Error invoking bsh method: source Sourced file: recorder.bsf : Typed variable declaration : Typed variable declaration : Attempt to resolve method: rightPad() on undefined variable or class name: StringUtils
2014/01/13 00:54:50 WARN  - jmeter.visualizers.BeanShellListener: Problem in BeanShell script org.apache.jorphan.util.JMeterException: Error invoking bsh method: source        Sourced file: recorder.bsf : Typed variable declaration : Typed variable declaration : Attempt to resolve method: rightPad() on undefined variable or class name: StringUtils
2014/01/13 00:54:50 INFO  - jmeter.threads.JMeterThread: Thread started: Moodle Test 2-4
2014/01/13 00:54:50 ERROR - jmeter.util.BeanShellInterpreter: Error invoking bsh method: source Sourced file: recorder.bsf : Typed variable declaration : Typed variable declaration : Attempt to resolve method: rightPad() on undefined variable or class name: StringUtils
2014/01/13 00:54:50 WARN  - jmeter.visualizers.BeanShellListener: Problem in BeanShell script org.apache.jorphan.util.JMeterException: Error invoking bsh method: source        Sourced file: recorder.bsf : Typed variable declaration : Typed variable declaration : Attempt to resolve method: rightPad() on undefined variable or class name: StringUtils
2014/01/13 00:54:50 INFO  - jmeter.threads.JMeterThread: Thread started: Moodle Test 2-5
2014/01/13 00:54:50 ERROR - jmeter.util.BeanShellInterpreter: Error invoking bsh method: source Sourced file: recorder.bsf : Typed variable declaration : Typed variable declaration : Attempt to resolve method: rightPad() on undefined variable or class name: StringUtils
2014/01/13 00:54:50 WARN  - jmeter.visualizers.BeanShellListener: Problem in BeanShell script org.apache.jorphan.util.JMeterException: Error invoking bsh method: source        Sourced file: recorder.bsf : Typed variable declaration : Typed variable declaration : Attempt to resolve method: rightPad() on undefined variable or class name: StringUtils
2014/01/13 00:54:50 INFO  - jmeter.threads.JMeterThread: Thread started: Moodle Test 2-6

**Comment by alendit** [comment]
Same error as @onno-schuit , both with JMeter 2.9 and 2.11 (java version "1.7.0_45").

**Comment by rajeshtaneja** [comment]
Hello Dimitri,

Have you downloaded the binaries from http://jmeter.apache.org/download_jmeter.cgi rather than using a package management system.

**Comment by tHeSmUrF** [comment]
Same error as what others have reported "jmeter.visualizers.BeanShellListener: Problem in BeanShell script org.apache.jorphan.util.JMeterException: Error invoking bsh method: source	Sourced file".

I've tried JMeter 2.12 and 2.9.

Running JDK 1.8.0.31

**Comment by rajeshtaneja** [comment]
Thanks for reporting this @tHeSmUrF 

Will check this ...

**Comment by dmonllao** [comment]
Hi @onno-schuit @alendit @tHeSmUrF,

The previous error this issue was solving was pretty clear, a change from lang to lang3, this seems to be a different issue.

I couldn't replicate the problem, I've tried using:
* Ubuntu 14.04
* OpenJDK "1.7.0_75"
* I've tried with JMeter 2.9, 2.11 and 2.12

Just a few questions?
* Do you experience the same problem if you just run ./compare.sh?
* Are you overwriting any defaults.properties value?

Resuming, do you always experience the same issue or only under specific conditions? TIA

**Comment by bodypheo** [comment]
Hi all,
I am still having this error with apache-jmeter when running the moodle test-plan.
2021-06-15 11:09:44,616 ERROR o.a.j.u.BeanShellInterpreter: Error invoking bsh method: source	/home/xxx/apache-jmeter-5.4.1/bin/recorder.bsf (No existe el fichero o el directorio) (file or directory does not exist)
recorder.bsf does not exist aI downloaded a 5.2.x with same result
Can this be fixed somehow?
I downloaded the jmeter tar from apache jmeter directly not from package manager.
Any ideas?

Thanks
Kind regards

**Comment by bodypheo** [comment]
Hi again,
after some trials and errors, (monkey behind keyboard), I have been able to run the tests changing this:
In Test Plan tree-> Moodle test -> Create php array results ->  in scrpt file name on Beanshell listener, changed recorder.bsf for the path to file: apache-jmeter-5.4.1/bin/BeanShellFunction.bshrc
Apparently it is working now, it is running the test and it is doing all the test, getting page courses, discussions etc.
Cheers

**Comment by stronk7** [comment]
Hi,

I'm closing this as far as the original problem reported here was fixed long, long ago.

@bodypheo , I'm no sure that changing `recorder.bsf` by `apache-jmeter-5.4.1/bin/BeanShellFunction.bshrc` is a valid solution. That recorder is in charge of extracting important information from Moodle pages (files included, db operations...) and switching to another recorder doesn't sound like a correct solution (all that information will be missed).

I've seen that you're using Jmeter 5.x... I'd suggest you to try with older versions (we are actively using Jmeter 2.9 (and 2.11) in our infrastructure. Maybe that's enough to get the Moodle plan (and results) running ok.

I'd recommend you to continue @ #71 where another problem with recent JMeter version has been reported. There is a link to the old JMeter binaries there.

Now, as said, closing this, ciao :-)

**Comment by bodypheo** [comment]
@stronk7 Thank you very much for your insights, I will take a look at what you suggest.
