### ISSUE TITLE
sudo delete_files not working

### ISSUE THREAD

**Issue by schach** [moodlehq/moodle-performance-comparison#47]
In clean_data.sh following calls don't work.
sudo delete_files "cache"
sudo delete_files "$backupsdir/*"
Looks like sudoing a bash function is not possible.

Replaced "delete_files" with "rm -rf" and removed the quotes to make it work:
sudo rm -rf cache
sudo rm -rf $backupsdir/*

**Comment by dmonllao** [comment]
Ok, then we could _sudo rm -rf cache_ instead of _sudo delete_files "cache"_, we would not need webapp/lib.php modifications in that case.

**Comment by dmonllao** [comment]
Hi @rajeshtaneja , I was just looking at the project issues, do you think of the _rm -rf cache_ approach?

**Comment by rajeshtaneja** [comment]
Thanks for looking at this David, this got lost somehow.

I still feel we should try avoid sudo where possible,  as these scripts are normally used by jobs. IMHO we should fix proper permission  and add information about removing old files in update.

**Comment by stronk7** [comment]
Yeah, I think we should avoid any sudo within any script. If the execution generate files owned by "apache/www", then it will need to be run by "apache/www" or by an user having perms to perform the clean (say, group.. or whatever).

Perhaps this is instead about to add, in instructions, the "detail" of which user should execute every script?

Note that, perhaps, an alternative would be to make this to be a local_xxx plugin, and to have some php scripts on it, able to be run from the browser, so they will be run with the "correct" user. Although I'm not 100% sold to this idea either. I think I prefer clearer specification, or error message if something was not deleted, saying "are you sure that you ran this with the xxxx user" or so.

Just my 2 cents. Ciao :)

**Comment by dmonllao** [comment]
I am not sure about the CLI scripts running by www-data user, the CLI scripts runs by a normal user, privileges over jmeter... and www-data runs only the web app, the issue here is that the web app fills a images cache dir, as it is a cache dir I thought that it should also be cleaned if we have a clean_data.sh script. About local_xxx, would be hard to make it possible as this projects needs full control over an empty clean moodle site, it needs to switch to other branches...

IMO given the size of the cache directory contents we could just leave the cache there or create another clean_webapp_data.sh

**Comment by dmonllao** [comment]
Proposal adding a new clean_webapp_data.sh

**Comment by rajeshtaneja** [comment]
I think it is nice solution, but surely would be good to fix permissions in webapp/lib.php
https://github.com/rajeshtaneja/moodle-performance-comparison/commit/ab22037f8d957c109ccf007881c3e1b521b4b5df

**Comment by dmonllao** [comment]
As commented in https://github.com/moodlehq/moodle-performance-comparison/issues/47#issuecomment-62337645 that would not be enough; up to you, whatever you decide I'm fine with it.

**Comment by rajeshtaneja** [comment]
Sure David, I am saying with your patch we should include fix for webapp/lib.php
That will not need clean_webapp_data.sh to be executed as sudo for later runs.

**Comment by dmonllao** [comment]
As discussed in HQ, I've added 3 branches (master, 28 and 27) including the new script and moving permissions to 775.

The new script, run by www-data, deletes cache/ (and if in future there are more temp dirs created by the web app) contents, also the ones created before this patch gets integrated.

In our nightly CI server we will:
* Run ./clean_webapp_data.sh manually using www-data user to clean all cache/ 755 contents
* Include jenkins and www-data in the same group (Rajesh is confident about this solution)
* In monthly basis, run ./clean_data.sh and ./clean_webapp_data.sh using jenkins user

**Comment by dmonllao** [comment]
The branches are
* git://github.com/dmonllao/moodle-performance-comparison issue-47-master
* git://github.com/dmonllao/moodle-performance-comparison issue-47-28
* git://github.com/dmonllao/moodle-performance-comparison issue-47-27

**Comment by rajeshtaneja** [comment]
Thanks David, 

Branches merged :)
