### ISSUE TITLE
non well-formed numeric value with PHP7

### ISSUE THREAD

**Issue by andrewnicols** [moodlehq/moodle-performance-comparison#58]
Notice: A non well formed numeric value encountered in /var/lib/jenkins/git_repositories/moodle-performance-comparison/webapp/classes/test_plan_runs.php on line 173
PHP Notice:  A non well formed numeric value encountered in /var/lib/jenkins/git_repositories/moodle-performance-comparison/webapp/classes/test_plan_runs.php on line 173

**Comment by dmonllao** [comment]
Fix for this in https://github.com/moodlehq/moodle-performance-comparison/pull/59, better to integrate after releasing.
